server.port: ${PORT}

currencyListener:
  baseUrl: ${CURRENCY_LISTENER_BASE_URL}
  subscribeUpdateUrl: subscribe/update
  unsubscribeUpdateUrl: unsubscribe/update
  subscribeFallUrl: subscribe/fall
  getOneUrl: /get?figi=



telegram.bot:

  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}

#  token: 1869011562:AAGTy1hnkUEuT-VvhVjgx-C1YuOSI0Cv8cQ
#  username: cryptoKosh_bot

  processed:
    command:
      start: /start
      subscribeFall: /subscribeFall
      subscribeUpdate: /subscribeUpdate
      unsubscribeUpdate: /unsubscribeUpdate
      update: /update
    text:
      iWantGetOne: Узнать текущий курс!
      iWantToSubscribeOnFall: Узнать, когда курс упадёт!
      iWantToSubscribeOnUpdate: Подписатьться на поток обновления курса!
      iWantToUnsubscribeOnUpdate: Отписаться от потока!

  blank:
    hello: |
      Привет, %s!
      Меня зовут cryptoKosh_bot.
      Я бот, который помогает тем, кто хочет знать самую актуальную информацию о курсе криптовалют.
      Здесь можно узнать курсы криптовалют, а также оформить подписку на обновления их курса.

    unknownCommand: Прости, я не понимаю тебя, у меня лапки. Пожалуйста воспользуйся командами, которые я уже выучил.

    unknownFormat: Не могу разобрать. Проверь, соответствует ли команда заданному формату.

    unknownCurrency: В моей базе этой валюты нет. Меня не проведёшь, ты её выдумал!

    fallPercentError: |
      Хм...
      Я не смог посчитать такой процент от текущего курса.
      Проверь, правильно ли ты его ввёл.
      И не забывай,
      что он может быть только в диапазоне от 0 до 100 :)

    guideSubscribeFall: |
      Тогда отправь мне команду:
      /subscribeFall <код валюты> <процент падения>

      например:
      /subscribeFall ETH 5

    successSubscribeFall: |
      Отлично!
      Теперь осталось только ждать. Как только %s упадёт на %s процентов, я пришлю тебе уведомление.

    guideSubscribeUpdate: |
      Тогда отправь мне команду:
      /subscribeUpdate <код валюты>

      например:
      /subscribeUpdate BTC

    successSubscribeUpdate: |
      Отлично!
      Теперь каждые 3 секунды ты будешь получать сообщение с текущим курсом %s.

    guideUnsubscribeUpdate: |
      Тогда отправь мне команду:
      /unsubscribeUpdate <код валюты>

      например:
      /unsubscribeUpdate BTC

    successUnsubscribeUpdate: |
      Эх...
      Больше тебе не будут приходить сообщения с курсом %s.
      Рад был помочь.

    guideGetOne: |
      Тогда отправь мне команду:
      /update <код валюты>

      например:
      /update BTC

    updateEvent: Стоимость %s составляет $%s
    fallEvent: Стоимость %s упала, и теперь составляет $%s
    errorEvent: Проверил? Меня не проведёшь! Нет такой валюты, ты её выдумал!